Adrien/deal for ob
mangrovedao/mangrove-ts pull request #1156
Opened 2023-02-24 16:51 UTC by adhusson

2023-02-27 08:43 UTC, peterMangrove requested changes

2023-02-27 08:43 UTC, peterMangrove commented on packages/mangrove.js/src/cli/commands/dealCmd.ts
> +  console.log("hey?");
Should this be removed

2023-02-27 08:43 UTC, peterMangrove commented on packages/mangrove.js/src/script.ts
> +console.log("hellO?");
Should this be removed?

2023-03-01 11:46 UTC, adhusson commented on packages/mangrove.js/src/cli/commands/dealCmd.ts
> +  console.log("hey?");
yes :D

2023-03-01 11:46 UTC, adhusson commented on packages/mangrove.js/src/script.ts
> +console.log("hellO?");
as well!

2023-03-01 11:46 UTC, adhusson commented on packages/mangrove.js/src/script.ts
> +console.log("hellO?");
the whole file actually

2023-03-01 12:14 UTC, merged