Feat/fix approve
mangrovedao/mangrove-ts pull request #1263
Opened 2023-05-12 13:06 UTC by jkrivine

This PR does the following (and replaces #1238 )

- OfferLogic has an `approve` function to ask the underlying logic to approve signer (or an arbitrary address) to spend a specific token on its behalf.
- Liquidity provider no longer provides `approveAsk`, `approveBids` which were making too much asumptions on router usage.
- Adapts tutorial scripts accordingly.
- bugfix: token approval could not be set to 0

2023-05-12 15:35 UTC, jkrivine commented
> lgtm. When this hits the docs repo, then some guides should be updated. Tagging @dontrolle just as an FYI

@dontrolle I updated the scripts used for the tutorials, I have not found anything in the docs that needs to be updated

2023-05-12 21:11 UTC, jkrivine commented
@peterMangrove I've added a regression test that fails. I don't understand why yet.

2023-05-15 07:03 UTC, peterMangrove requested changes

2023-05-15 07:03 UTC, peterMangrove commented on packages/mangrove.js/test/integration/offermaker.integration.test.ts
> +        assert.equal(allowance, 42, "Invalid allowance");
The allowance is of type "Big", i don't think big and number can be compared.

2023-05-16 09:38 UTC, jkrivine commented on packages/mangrove.js/test/integration/offermaker.integration.test.ts
> +        assert.equal(allowance, 42, "Invalid allowance");
Seems to work at leat :)

2023-05-16 10:26 UTC, peterMangrove approved these changes

2023-05-16 10:26 UTC, merged