Feat/kandelprovision2
mangrovedao/mangrove-ts pull request #1290
Opened 2023-05-23 12:49 UTC by lnist

2023-05-23 13:08 UTC, peterMangrove requested changes
lgtm. Only a few comments

2023-05-23 13:08 UTC, peterMangrove commented on packages/mangrove.js/src/kandel/kandelInstance.ts
> +    }));
Consider moving this to its own method, as you are doing this in at least 2 places.

2023-05-24 07:02 UTC, lnist commented on packages/mangrove.js/src/kandel/kandelInstance.ts
> +   * @returns the locked provision, in ethers.
yes, it's what we use in multiple places.

2023-05-24 07:04 UTC, lnist commented on packages/mangrove.js/src/kandel/kandelInstance.ts
> +    return this.market.mgv.calculateOffersProvision(existingOffers);
Good point, fixing.

2023-05-24 07:04 UTC, lnist commented on packages/mangrove.js/src/kandel/kandelInstance.ts
> +  /** Gets the missing provision based on provision already available on Mangrove, potentially locked by existing offers. It assumes all locked provision will be made available via deprovision of due
Yse :)

2023-05-24 07:19 UTC, lnist commented on packages/mangrove.js/src/kandel/kandelInstance.ts
> +    }));
done

2023-05-24 07:23 UTC, peterMangrove approved these changes

2023-05-24 07:31 UTC, merged