feat(restingOrder): Upgrade to new mangrove-core supporting expiry as a timestamp
mangrovedao/mangrove-ts pull request #870
Opened 2022-11-17 11:14 UTC by lnist

… a timestamp

2022-11-17 12:39 UTC, adhusson commented on packages/mangrove.js/src/market.ts
> +      txPromise
the prettification makes it difficult to understand what has changed

2022-11-17 12:39 UTC, adhusson commented on packages/mangrove.js/src/market.ts
> +          txHashDeferred.reject(e);
yes seems good! agreed that this is just cleaning up our objects and there is no behavior change, right?

2022-11-17 12:39 UTC, adhusson commented on packages/mangrove.js/src/offerLogic.ts
> +      await this.mgv._signer.getAddress(),
not sure what this is for

2022-11-17 12:39 UTC, adhusson commented on packages/mangrove.js/test/unit/trade.unit.test.ts
> +        BigNumber.from(expectedGivesWithoutSlippage.toFixed(0)).eq(
why did the equality test change from
`a.eq(b)` to `BigNumber.from(b.toFixed(0)).eq(a'))` ?

2022-11-17 12:43 UTC, lnist commented on packages/mangrove.js/src/offerLogic.ts
> +      await this.mgv._signer.getAddress(),
the tokenBalance now takes a maker as a parameter.

2022-11-17 12:53 UTC, lnist commented on packages/mangrove.js/src/market.ts
> +      txPromise
yeah - I use kdiff3 to get something meaningful. See slack :)

2022-11-17 13:39 UTC, jkrivine requested changes
Looks good to me except maybe a minor change in `tokenBalance`

2022-11-17 13:39 UTC, jkrivine commented on packages/mangrove.js/src/offerLogic.ts
> +      await this.mgv._signer.getAddress(),
I think tokenBalance should have an optional `maker` parameter. If none are provided then `this.mgv._signer.getAddress()` should be used

2022-11-17 17:46 UTC, adhusson commented on packages/mangrove.js/src/market.ts
> +                  throw e;
I think it's actually fine without it... sorry!

2022-11-18 08:41 UTC, lnist commented on packages/mangrove.js/src/market.ts
> +                  throw e;
removed :)

2022-11-18 11:16 UTC, jkrivine approved these changes

2022-11-18 11:16 UTC, merged