fix(test): Make proxy between tests and anvil to allow closure
mangrovedao/mangrove-ts pull request #876
Opened 2022-11-21 14:51 UTC by lnist

Integration tests run against an anvil instance. We use snapshots and in `beforeEach` we revert to a previous, good, snapshot before starting each test.

However, the prior test can have outstanding RPC requests towards the anvil instance and these can complete _after_ the revert, causing changes to anvil state.

We now proxy all requests through a proxy and close it for further requests and wait for outstanding requests before reverting.

This fixes sporadic test failures like
https://github.com/mangrovedao/mangrove-ts/actions/runs/3410881559/jobs/5674398420
and
https://github.com/mangrovedao/mangrove-ts/actions/runs/3411610454/jobs/5676045661
where revert does not do its job.

2022-11-21 15:14 UTC, adhusson approved these changes
Great catch. Also super clean&short implementation of something that seemed daunting when I read the description.

2022-11-21 15:14 UTC, adhusson commented on packages/mangrove.js/src/util/node.ts
> +      const bn = await params.provider.perform("getBlockNumber", {});
why `getBlockNumber` -> `perform("getBlockNumber)`?

2022-11-21 15:14 UTC, adhusson commented on packages/mangrove.js/src/util/node.ts
> +          `evm_revert aadid not revert to expected block number ${snapshotBlockNumber} but to ${blockNumberAfterRevert}. Snapshots are deleted when reverting - did you take a new snapshot after the l
I think some vim commands have sneaked up here :)

2022-11-21 15:18 UTC, lnist commented on packages/mangrove.js/src/util/node.ts
> +          `evm_revert aadid not revert to expected block number ${snapshotBlockNumber} but to ${blockNumberAfterRevert}. Snapshots are deleted when reverting - did you take a new snapshot after the l
Sorry - note.ts should almost not have been updated. Fixed.

2022-11-21 15:21 UTC, adhusson requested changes
Small change for port consistency

2022-11-21 15:21 UTC, adhusson commented on packages/mangrove.js/src/util/test/mochaHooks.ts
> +        return "127.0.0.1:8545";
Shouldn't this be
```suggestion
        return `${serverParams.host}:${serverParams.port}`;
```

2022-11-22 08:46 UTC, adhusson approved these changes

2022-11-22 08:46 UTC, merged