refactoring w.r.t new abi
mangrovedao/mangrove-ts pull request #893
Opened 2022-11-30 14:51 UTC by jkrivine

2022-12-01 07:53 UTC, lnist requested changes
I really like the simplifications!

2022-12-01 07:53 UTC, lnist commented on package.json
> +        "@mangrovedao/mangrove-core": "portal:/Users/jeankrivine/Documents/git/mangrove-core"
remember to revert this - ideally it should not have been pushed :)

2022-12-01 07:53 UTC, lnist commented on packages/mangrove.js/src/liquidityProvider.ts
> +    let poster = this.logic ? this.logic : this.mgv;
add .contract here like other places?

2022-12-01 07:53 UTC, lnist commented on packages/mangrove.js/src/liquidityProvider.ts
> -      const offer = await this.market.offerInfo(ba, opts.id);
Can we take this over coffee? :)

2022-12-01 10:27 UTC, jkrivine commented on packages/mangrove.js/src/liquidityProvider.ts
> -      const offer = await this.market.offerInfo(ba, opts.id);
yes. I am just utilising here the function `provisionOf` that is Forwarder/Direct compatible

2022-12-05 08:46 UTC, lnist requested changes

2022-12-05 08:46 UTC, lnist commented on packages/mangrove.js/src/util/trade.ts
> +            ba: bs === "buy" ? "asks" : "bids",
I've added a BsToBa function you can use for this

2022-12-05 08:46 UTC, lnist commented on packages/mangrove.js/src/util/trade.ts
> +    await market.consoleAsks(["wants", "gives"]);
this should not be pushed

2022-12-05 08:46 UTC, lnist commented on packages/mangrove.js/test/unit/mangrove.unit.test.ts
>        }).connect();
why this change? 8544 would probably be even better to not clash with other tests.

2022-12-05 08:46 UTC, lnist commented on packages/mangrove.js/src/util/trade.ts
> +  order(
In the past there was some switching gives and wants around depending on buy/sell. I assume all that is still taken care of. It is great we got this simplified!

2022-12-05 13:12 UTC, jkrivine commented on packages/mangrove.js/src/util/trade.ts
> +  order(
This is taken care line 151

2022-12-05 13:37 UTC, peterMangrove commented on packages/mangrove.js/src/market.ts
> +    fillOrKill?: boolean;
Does it make sense, that you now can both do a FoK and restingorder?

2022-12-05 14:37 UTC, lnist approved these changes

2022-12-06 10:06 UTC, jkrivine commented on packages/mangrove.js/src/market.ts
> +    fillOrKill?: boolean;
At least this has an interpretation by the backend: revert if partialFill & resting order failed to be posted

2022-12-06 13:16 UTC, merged