feat: Added allowed routes to TradeParams
mangrovedao/mangrove-ts pull request #924
Opened 2022-12-27 11:38 UTC by peterMangrove

2022-12-27 20:01 UTC, espendk requested changes
I think the `OrderRoute` solution will take more work to get good, so I suggest we use a simple flag to force routing of orders to `MangroveOrder` instead, see the code comments.

2022-12-27 20:01 UTC, espendk commented on packages/mangrove.js/src/util/trade.ts
> +      }
This can be reverted I think

2022-12-27 20:01 UTC, espendk commented on packages/mangrove.js/src/util/trade.ts
> +        }
This can be reverted I think

2022-12-28 10:06 UTC, peterMangrove commented on packages/mangrove.js/src/util/trade.ts
> +      }
Done

2022-12-28 10:06 UTC, peterMangrove commented on packages/mangrove.js/src/util/trade.ts
> +        }
Done

2022-12-28 10:06 UTC, peterMangrove commented on packages/mangrove.js/src/util/trade.ts
>      if (params.fillOrKill || restingOrderParams) {
Done

2022-12-28 10:08 UTC, peterMangrove commented on packages/mangrove.js/src/util/trade.ts
>      if (params.fillOrKill || restingOrderParams) {
Done

2022-12-28 10:08 UTC, peterMangrove commented on packages/mangrove.js/src/market.ts
> +    allowedOrderRoutes?: OrderRoute[];
Done

2022-12-28 10:08 UTC, peterMangrove commented on packages/mangrove.js/src/market.ts
> +
Done

2022-12-28 11:48 UTC, espendk requested changes

2022-12-28 11:48 UTC, espendk commented on packages/mangrove.js/src/util/trade.ts
> +      (params.forceRoutingToMangroveOrder ?? false)
`fillOrKill` and `forceRoutingToMangroveOrder` are both optional booleans, so they should be treated the same here. I think the idiomatic way would be to use `!!optionalBoolean`, ie `!!params.fillOrKill` and `!!params.forceRoutingToMangroveOrder`.

2022-12-28 12:08 UTC, espendk approved these changes

2022-12-28 12:46 UTC, merged