feat: Change order to return result and response as promises
mangrovedao/mangrove-ts pull request #925
Opened 2022-12-27 13:10 UTC by peterMangrove

2022-12-27 13:11 UTC, peterMangrove commented
Fixes part of https://github.com/mangrovedao/mangrove-ts/issues/173
Should fix https://github.com/mangrovedao/mangrove-dApp/issues/204

2022-12-27 21:04 UTC, espendk requested changes
lgtm! Some smaller comments

2022-12-28 08:40 UTC, peterMangrove commented on packages/mangrove.js/src/util/trade.ts
> +    });
Its a mistake, only one is needed. I have removed one

2022-12-28 08:40 UTC, peterMangrove commented on packages/mangrove.js/test/integration/market.integration.test.ts
> +import { builtinModules } from "module";
No, i have removed the import

2022-12-28 09:45 UTC, espendk approved these changes

2022-12-28 13:03 UTC, merged